/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Console Variables
 * @export
 * @interface ConsoleVariables
 */
export interface ConsoleVariables {
    /**
     * CNAME target for your Appwrite custom domains.
     * @type {string}
     * @memberof ConsoleVariables
     */
    '_APP_DOMAIN_TARGET': string;
    /**
     * Maximum file size allowed for file upload in bytes.
     * @type {number}
     * @memberof ConsoleVariables
     */
    '_APP_STORAGE_LIMIT': number;
    /**
     * Maximum file size allowed for deployment in bytes.
     * @type {number}
     * @memberof ConsoleVariables
     */
    '_APP_FUNCTIONS_SIZE_LIMIT': number;
    /**
     * Defines if usage stats are enabled. This value is set to \'enabled\' by default, to disable the usage stats set the value to \'disabled\'.
     * @type {string}
     * @memberof ConsoleVariables
     */
    '_APP_USAGE_STATS': string;
    /**
     * Defines if VCS (Version Control System) is enabled.
     * @type {boolean}
     * @memberof ConsoleVariables
     */
    '_APP_VCS_ENABLED': boolean;
    /**
     * Defines if main domain is configured. If so, custom domains can be created.
     * @type {boolean}
     * @memberof ConsoleVariables
     */
    '_APP_DOMAIN_ENABLED': boolean;
    /**
     * Defines if AI assistant is enabled.
     * @type {boolean}
     * @memberof ConsoleVariables
     */
    '_APP_ASSISTANT_ENABLED': boolean;
}

