/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Installation
 * @export
 * @interface Installation
 */
export interface Installation {
    /**
     * Function ID.
     * @type {string}
     * @memberof Installation
     */
    '$id': string;
    /**
     * Function creation date in ISO 8601 format.
     * @type {string}
     * @memberof Installation
     */
    '$createdAt': string;
    /**
     * Function update date in ISO 8601 format.
     * @type {string}
     * @memberof Installation
     */
    '$updatedAt': string;
    /**
     * VCS (Version Control System) provider name.
     * @type {string}
     * @memberof Installation
     */
    'provider': string;
    /**
     * VCS (Version Control System) organization name.
     * @type {string}
     * @memberof Installation
     */
    'organization': string;
    /**
     * VCS (Version Control System) installation ID.
     * @type {string}
     * @memberof Installation
     */
    'providerInstallationId': string;
}

