/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Key
 * @export
 * @interface Key
 */
export interface Key {
    /**
     * Key ID.
     * @type {string}
     * @memberof Key
     */
    '$id': string;
    /**
     * Key creation date in ISO 8601 format.
     * @type {string}
     * @memberof Key
     */
    '$createdAt': string;
    /**
     * Key update date in ISO 8601 format.
     * @type {string}
     * @memberof Key
     */
    '$updatedAt': string;
    /**
     * Key name.
     * @type {string}
     * @memberof Key
     */
    'name': string;
    /**
     * Key expiration date in ISO 8601 format.
     * @type {string}
     * @memberof Key
     */
    'expire': string;
    /**
     * Allowed permission scopes.
     * @type {Array<string>}
     * @memberof Key
     */
    'scopes': Array<string>;
    /**
     * Secret key.
     * @type {string}
     * @memberof Key
     */
    'secret': string;
    /**
     * Most recent access date in ISO 8601 format. This attribute is only updated again after 24 hours.
     * @type {string}
     * @memberof Key
     */
    'accessedAt': string;
    /**
     * List of SDK user agents that used this key.
     * @type {Array<string>}
     * @memberof Key
     */
    'sdks': Array<string>;
}

