/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingUpdatePushMessageRequest
 */
export interface MessagingUpdatePushMessageRequest {
    /**
     * Title for push notification.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'title'?: string;
    /**
     * List of Topic IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'topics'?: Array<string>;
    /**
     * List of User IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'users'?: Array<string>;
    /**
     * List of Targets IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'targets'?: Array<string>;
    /**
     * Body for push notification.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'body'?: string;
    /**
     * Additional Data for push notification.
     * @type {object}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'data'?: object;
    /**
     * Action for push notification.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'action'?: string;
    /**
     * Image for push notification. Must be a compound bucket ID to file ID of a jpeg, png, or bmp image in Appwrite Storage.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'image'?: string;
    /**
     * Icon for push notification. Available only for Android and Web platforms.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'icon'?: string;
    /**
     * Sound for push notification. Available only for Android and iOS platforms.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'sound'?: string;
    /**
     * Color for push notification. Available only for Android platforms.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'color'?: string;
    /**
     * Tag for push notification. Available only for Android platforms.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'tag'?: string;
    /**
     * Badge for push notification. Available only for iOS platforms.
     * @type {number}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'badge'?: number;
    /**
     * Is message a draft
     * @type {boolean}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'draft'?: boolean;
    /**
     * Scheduled delivery time for message in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. DateTime value must be in future.
     * @type {string}
     * @memberof MessagingUpdatePushMessageRequest
     */
    'scheduledAt'?: string;
}

