/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metric
 * @export
 * @interface Metric
 */
export interface Metric {
    /**
     * The value of this metric at the timestamp.
     * @type {number}
     * @memberof Metric
     */
    'value': number;
    /**
     * The date at which this metric was aggregated in ISO 8601 format.
     * @type {string}
     * @memberof Metric
     */
    'date': string;
}

