/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Migration
 * @export
 * @interface Migration
 */
export interface Migration {
    /**
     * Migration ID.
     * @type {string}
     * @memberof Migration
     */
    '$id': string;
    /**
     * Variable creation date in ISO 8601 format.
     * @type {string}
     * @memberof Migration
     */
    '$createdAt': string;
    /**
     * Variable creation date in ISO 8601 format.
     * @type {string}
     * @memberof Migration
     */
    '$updatedAt': string;
    /**
     * Migration status ( pending, processing, failed, completed ) 
     * @type {string}
     * @memberof Migration
     */
    'status': string;
    /**
     * Migration stage ( init, processing, source-check, destination-check, migrating, finished )
     * @type {string}
     * @memberof Migration
     */
    'stage': string;
    /**
     * A string containing the type of source of the migration.
     * @type {string}
     * @memberof Migration
     */
    'source': string;
    /**
     * Resources to migration.
     * @type {Array<string>}
     * @memberof Migration
     */
    'resources': Array<string>;
    /**
     * A group of counters that represent the total progress of the migration.
     * @type {object}
     * @memberof Migration
     */
    'statusCounters': object;
    /**
     * An array of objects containing the report data of the resources that were migrated.
     * @type {object}
     * @memberof Migration
     */
    'resourceData': object;
    /**
     * All errors that occurred during the migration process.
     * @type {Array<string>}
     * @memberof Migration
     */
    'errors': Array<string>;
}

