/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MigrationsCreateNHostMigrationRequest
 */
export interface MigrationsCreateNHostMigrationRequest {
    /**
     * List of resources to migrate
     * @type {Array<string>}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'resources': Array<string>;
    /**
     * Source\'s Subdomain
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'subdomain': string;
    /**
     * Source\'s Region
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'region': string;
    /**
     * Source\'s Admin Secret
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'adminSecret': string;
    /**
     * Source\'s Database Name
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'database': string;
    /**
     * Source\'s Database Username
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'username': string;
    /**
     * Source\'s Database Password
     * @type {string}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'password': string;
    /**
     * Source\'s Database Port
     * @type {number}
     * @memberof MigrationsCreateNHostMigrationRequest
     */
    'port'?: number;
}

