/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Migration Report
 * @export
 * @interface MigrationReport
 */
export interface MigrationReport {
    /**
     * Version of the Appwrite instance to be migrated.
     * @type {string}
     * @memberof MigrationReport
     */
    'version': string;
    /**
     * Number of users to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'user': number;
    /**
     * Number of teams to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'team': number;
    /**
     * Number of databases to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'database': number;
    /**
     * Number of documents to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'document': number;
    /**
     * Number of files to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'file': number;
    /**
     * Number of buckets to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'bucket': number;
    /**
     * Number of functions to be migrated.
     * @type {number}
     * @memberof MigrationReport
     */
    'function': number;
    /**
     * Size of files to be migrated in mb.
     * @type {number}
     * @memberof MigrationReport
     */
    'size': number;
}

