/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Platform
 * @export
 * @interface Platform
 */
export interface Platform {
    /**
     * Platform ID.
     * @type {string}
     * @memberof Platform
     */
    '$id': string;
    /**
     * Platform creation date in ISO 8601 format.
     * @type {string}
     * @memberof Platform
     */
    '$createdAt': string;
    /**
     * Platform update date in ISO 8601 format.
     * @type {string}
     * @memberof Platform
     */
    '$updatedAt': string;
    /**
     * Platform name.
     * @type {string}
     * @memberof Platform
     */
    'name': string;
    /**
     * Platform type. Possible values are: web, flutter-web, flutter-ios, flutter-android, ios, android, and unity.
     * @type {string}
     * @memberof Platform
     */
    'type': string;
    /**
     * Platform Key. iOS bundle ID or Android package name.  Empty string for other platforms.
     * @type {string}
     * @memberof Platform
     */
    'key': string;
    /**
     * App store or Google Play store ID.
     * @type {string}
     * @memberof Platform
     */
    'store': string;
    /**
     * Web app hostname. Empty string for other platforms.
     * @type {string}
     * @memberof Platform
     */
    'hostname': string;
    /**
     * HTTP basic authentication username.
     * @type {string}
     * @memberof Platform
     */
    'httpUser': string;
    /**
     * HTTP basic authentication password.
     * @type {string}
     * @memberof Platform
     */
    'httpPass': string;
}

