/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsUpdateCustomEmailTemplatesRequest
 */
export interface ProjectsUpdateCustomEmailTemplatesRequest {
    /**
     * Email Subject
     * @type {string}
     * @memberof ProjectsUpdateCustomEmailTemplatesRequest
     */
    'subject': string;
    /**
     * Template message
     * @type {string}
     * @memberof ProjectsUpdateCustomEmailTemplatesRequest
     */
    'message': string;
    /**
     * Name of the email sender
     * @type {string}
     * @memberof ProjectsUpdateCustomEmailTemplatesRequest
     */
    'senderName'?: string;
    /**
     * Email of the sender
     * @type {string}
     * @memberof ProjectsUpdateCustomEmailTemplatesRequest
     */
    'senderEmail'?: string;
    /**
     * Reply to email
     * @type {string}
     * @memberof ProjectsUpdateCustomEmailTemplatesRequest
     */
    'replyTo'?: string;
}

