/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsCreateWebhookRequest
 */
export interface ProjectsCreateWebhookRequest {
    /**
     * Certificate verification, false for disabled or true for enabled.
     * @type {boolean}
     * @memberof ProjectsCreateWebhookRequest
     */
    'security': boolean;
    /**
     * Webhook name. Max length: 128 chars.
     * @type {string}
     * @memberof ProjectsCreateWebhookRequest
     */
    'name': string;
    /**
     * Enable or disable a webhook.
     * @type {boolean}
     * @memberof ProjectsCreateWebhookRequest
     */
    'enabled'?: boolean;
    /**
     * Events list. Maximum of 100 events are allowed.
     * @type {Array<string>}
     * @memberof ProjectsCreateWebhookRequest
     */
    'events': Array<string>;
    /**
     * Webhook URL.
     * @type {string}
     * @memberof ProjectsCreateWebhookRequest
     */
    'url': string;
    /**
     * Webhook HTTP user. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsCreateWebhookRequest
     */
    'httpUser'?: string;
    /**
     * Webhook HTTP password. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsCreateWebhookRequest
     */
    'httpPass'?: string;
}

