/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsCreateSmtpTestRequest
 */
export interface ProjectsCreateSmtpTestRequest {
    /**
     * Array of emails to send test email to. Maximum of 10 emails are allowed.
     * @type {Array<string>}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'emails': Array<string>;
    /**
     * Name of the email sender
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'senderName': string;
    /**
     * Email of the sender
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'senderEmail': string;
    /**
     * Reply to email
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'replyTo'?: string;
    /**
     * SMTP server host name
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'host': string;
    /**
     * SMTP server port
     * @type {number}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'port'?: number;
    /**
     * SMTP server username
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'username'?: string;
    /**
     * SMTP server password
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'password'?: string;
    /**
     * Does SMTP server use secure connection
     * @type {string}
     * @memberof ProjectsCreateSmtpTestRequest
     */
    'secure'?: ProjectsCreateSmtpTestRequestSecureEnum;
}

type ProjectsCreateSmtpTestRequestSecureEnum = 'tls'


