/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsUpdatePlatformByIdRequest
 */
export interface ProjectsUpdatePlatformByIdRequest {
    /**
     * Platform name. Max length: 128 chars.
     * @type {string}
     * @memberof ProjectsUpdatePlatformByIdRequest
     */
    'name': string;
    /**
     * Package name for android or bundle ID for iOS. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsUpdatePlatformByIdRequest
     */
    'key'?: string;
    /**
     * App store or Google Play store ID. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsUpdatePlatformByIdRequest
     */
    'store'?: string;
    /**
     * Platform client URL. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsUpdatePlatformByIdRequest
     */
    'hostname'?: string;
}

