/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsCreatePlatformRequest
 */
export interface ProjectsCreatePlatformRequest {
    /**
     * Platform type.
     * @type {string}
     * @memberof ProjectsCreatePlatformRequest
     */
    'type': ProjectsCreatePlatformRequestTypeEnum;
    /**
     * Platform name. Max length: 128 chars.
     * @type {string}
     * @memberof ProjectsCreatePlatformRequest
     */
    'name': string;
    /**
     * Package name for Android or bundle ID for iOS or macOS. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsCreatePlatformRequest
     */
    'key'?: string;
    /**
     * App store or Google Play store ID. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsCreatePlatformRequest
     */
    'store'?: string;
    /**
     * Platform client hostname. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsCreatePlatformRequest
     */
    'hostname'?: string;
}

type ProjectsCreatePlatformRequestTypeEnum = 'web' | 'flutter-web' | 'flutter-ios' | 'flutter-android' | 'flutter-linux' | 'flutter-macos' | 'flutter-windows' | 'apple-ios' | 'apple-macos' | 'apple-watchos' | 'apple-tvos' | 'android' | 'unity'


