/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsCreateKeyRequest
 */
export interface ProjectsCreateKeyRequest {
    /**
     * Key name. Max length: 128 chars.
     * @type {string}
     * @memberof ProjectsCreateKeyRequest
     */
    'name': string;
    /**
     * Key scopes list. Maximum of 100 scopes are allowed.
     * @type {Array<string>}
     * @memberof ProjectsCreateKeyRequest
     */
    'scopes': Array<string>;
    /**
     * Expiration time in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. Use null for unlimited expiration.
     * @type {string}
     * @memberof ProjectsCreateKeyRequest
     */
    'expire'?: string;
}

