/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsUpdateOAuthRequest
 */
export interface ProjectsUpdateOAuthRequest {
    /**
     * Provider Name
     * @type {string}
     * @memberof ProjectsUpdateOAuthRequest
     */
    'provider': ProjectsUpdateOAuthRequestProviderEnum;
    /**
     * Provider app ID. Max length: 256 chars.
     * @type {string}
     * @memberof ProjectsUpdateOAuthRequest
     */
    'appId'?: string;
    /**
     * Provider secret key. Max length: 512 chars.
     * @type {string}
     * @memberof ProjectsUpdateOAuthRequest
     */
    'secret'?: string;
    /**
     * Provider status. Set to \'false\' to disable new session creation.
     * @type {boolean}
     * @memberof ProjectsUpdateOAuthRequest
     */
    'enabled'?: boolean;
}

type ProjectsUpdateOAuthRequestProviderEnum = 'amazon' | 'apple' | 'auth0' | 'authentik' | 'autodesk' | 'bitbucket' | 'bitly' | 'box' | 'dailymotion' | 'discord' | 'disqus' | 'dropbox' | 'etsy' | 'facebook' | 'github' | 'gitlab' | 'google' | 'linkedin' | 'microsoft' | 'notion' | 'oidc' | 'okta' | 'paypal' | 'paypalSandbox' | 'podio' | 'salesforce' | 'slack' | 'spotify' | 'stripe' | 'tradeshift' | 'tradeshiftBox' | 'twitch' | 'wordpress' | 'yahoo' | 'yammer' | 'yandex' | 'zoho' | 'zoom' | 'mock'


