/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * ProviderRepository
 * @export
 * @interface ProviderRepository
 */
export interface ProviderRepository {
    /**
     * VCS (Version Control System) repository ID.
     * @type {string}
     * @memberof ProviderRepository
     */
    'id': string;
    /**
     * VCS (Version Control System) repository name.
     * @type {string}
     * @memberof ProviderRepository
     */
    'name': string;
    /**
     * VCS (Version Control System) organization name
     * @type {string}
     * @memberof ProviderRepository
     */
    'organization': string;
    /**
     * VCS (Version Control System) provider name.
     * @type {string}
     * @memberof ProviderRepository
     */
    'provider': string;
    /**
     * Is VCS (Version Control System) repository private?
     * @type {boolean}
     * @memberof ProviderRepository
     */
    'private': boolean;
    /**
     * Auto-detected runtime suggestion. Empty if getting response of getRuntime().
     * @type {string}
     * @memberof ProviderRepository
     */
    'runtime': string;
    /**
     * Last commit date in ISO 8601 format.
     * @type {string}
     * @memberof ProviderRepository
     */
    'pushedAt': string;
}

