/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Metric } from './metric';

/**
 * UsageDatabase
 * @export
 * @interface UsageDatabase
 */
export interface UsageDatabase {
    /**
     * Time range of the usage stats.
     * @type {string}
     * @memberof UsageDatabase
     */
    'range': string;
    /**
     * Total aggregated number of collections.
     * @type {number}
     * @memberof UsageDatabase
     */
    'collectionsTotal': number;
    /**
     * Total aggregated number of documents.
     * @type {number}
     * @memberof UsageDatabase
     */
    'documentsTotal': number;
    /**
     * Aggregated  number of collections per period.
     * @type {Array<Metric>}
     * @memberof UsageDatabase
     */
    'collections': Array<Metric>;
    /**
     * Aggregated  number of documents per period.
     * @type {Array<Metric>}
     * @memberof UsageDatabase
     */
    'documents': Array<Metric>;
}

