/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Metric } from './metric';

/**
 * StorageUsage
 * @export
 * @interface UsageStorage
 */
export interface UsageStorage {
    /**
     * Time range of the usage stats.
     * @type {string}
     * @memberof UsageStorage
     */
    'range': string;
    /**
     * Total aggregated number of buckets
     * @type {number}
     * @memberof UsageStorage
     */
    'bucketsTotal': number;
    /**
     * Total aggregated number of files.
     * @type {number}
     * @memberof UsageStorage
     */
    'filesTotal': number;
    /**
     * Total aggregated number of files storage (in bytes).
     * @type {number}
     * @memberof UsageStorage
     */
    'filesStorageTotal': number;
    /**
     * Aggregated number of buckets per period.
     * @type {Array<Metric>}
     * @memberof UsageStorage
     */
    'buckets': Array<Metric>;
    /**
     * Aggregated number of files per period.
     * @type {Array<Metric>}
     * @memberof UsageStorage
     */
    'files': Array<Metric>;
    /**
     * Aggregated number of files storage (in bytes) per period .
     * @type {Array<Metric>}
     * @memberof UsageStorage
     */
    'storage': Array<Metric>;
}

