/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Metric } from './metric';

/**
 * UsageBuckets
 * @export
 * @interface UsageBuckets
 */
export interface UsageBuckets {
    /**
     * Time range of the usage stats.
     * @type {string}
     * @memberof UsageBuckets
     */
    'range': string;
    /**
     * Total aggregated number of bucket files.
     * @type {number}
     * @memberof UsageBuckets
     */
    'filesTotal': number;
    /**
     * Total aggregated number of bucket files storage (in bytes).
     * @type {number}
     * @memberof UsageBuckets
     */
    'filesStorageTotal': number;
    /**
     * Aggregated  number of bucket files per period.
     * @type {Array<Metric>}
     * @memberof UsageBuckets
     */
    'files': Array<Metric>;
    /**
     * Aggregated  number of bucket storage files (in bytes) per period.
     * @type {Array<Metric>}
     * @memberof UsageBuckets
     */
    'storage': Array<Metric>;
}

