/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Webhook
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * Indicated if SSL / TLS Certificate verification is enabled.
     * @type {boolean}
     * @memberof Webhook
     */
    'security': boolean;
    /**
     * Webhook ID.
     * @type {string}
     * @memberof Webhook
     */
    '$id': string;
    /**
     * Webhook creation date in ISO 8601 format.
     * @type {string}
     * @memberof Webhook
     */
    '$createdAt': string;
    /**
     * Webhook update date in ISO 8601 format.
     * @type {string}
     * @memberof Webhook
     */
    '$updatedAt': string;
    /**
     * Webhook name.
     * @type {string}
     * @memberof Webhook
     */
    'name': string;
    /**
     * Webhook URL endpoint.
     * @type {string}
     * @memberof Webhook
     */
    'url': string;
    /**
     * Webhook trigger events.
     * @type {Array<string>}
     * @memberof Webhook
     */
    'events': Array<string>;
    /**
     * HTTP basic authentication username.
     * @type {string}
     * @memberof Webhook
     */
    'httpUser': string;
    /**
     * HTTP basic authentication password.
     * @type {string}
     * @memberof Webhook
     */
    'httpPass': string;
    /**
     * Signature key which can be used to validated incoming
     * @type {string}
     * @memberof Webhook
     */
    'signatureKey': string;
    /**
     * Indicates if this webhook is enabled.
     * @type {boolean}
     * @memberof Webhook
     */
    'enabled': boolean;
    /**
     * Webhook error logs from the most recent failure.
     * @type {string}
     * @memberof Webhook
     */
    'logs': string;
    /**
     * Number of consecutive failed webhook attempts.
     * @type {number}
     * @memberof Webhook
     */
    'attempts': number;
}

